# Generated by Django 4.2 on 2024-10-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storagemanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
