# Generated by Django 4.2 on 2024-11-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storagemanager", "0002_object_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="object_image",
            field=models.ImageField(blank=True, default="", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_image",
            field=models.ImageField(blank=True, default="", upload_to="images/"),
        ),
    ]
