# Generated by Django 4.2 on 2024-11-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storagemanager", "0003_object_object_image_unit_unit_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="object_image",
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_image",
            field=models.ImageField(default="images/box-open.svg", upload_to="images/"),
        ),
    ]
